version: "3.8"

services:
  autodarts:
    image: ghcr.io/markhaehnel/autodarts:latest
    # or build the image yourself
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - 3180:3180
    devices:
      # Add all video devices you want to use
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      # - /dev/video3:/dev/video3
      # - /dev/video4:/dev/video4
      # - /dev/video5:/dev/video5
    restart: always
    volumes:
      - autodarts_data:/home/autodarts/.config/autodarts

volumes:
  autodarts_data:
