name: Build Docker Images
on:
  workflow_dispatch:
    inputs:
      autodarts_version:
        description: 'Autodarts version'
        required: true

jobs:
  build-image:
    name: Build Image

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - run: echo "Building Docker image for autodarts version ${{ github.event.inputs.autodarts_version }}"

      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: '"markhaehnel/autodarts:${{ github.event.inputs.autodarts_version }}","markhaehnel/autodarts:latest"'
