name: Build Docker Images
on:
  workflow_dispatch:
    inputs:
      autodarts_version:
        description: 'Autodarts version'
        required: true
        type: string

jobs:
  build-image:
    name: Build Image

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - run: echo "Building Docker image for autodarts version ${{ github.event.inputs.autodarts_version }}"

      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: AUTODARTS_VERSION=${{ github.event.inputs.autodarts_version }}
          platforms: linux/amd64,linux/arm64
          tags: '"ghcr.io/markhaehnel/autodarts:${{ github.event.inputs.autodarts_version }}","ghcr.io/markhaehnel/autodarts:latest"'
